#!/bin/sh
name="agetty"
agetty="/sbin/agetty"

if [ "$1" != "start" ] ; then
    exit 0
fi

respawn(){
    while true ; do
        $*
        sleep 0.1
    done
}

# start all tty sessions
for tty in 1 2 3 4 5 6 ; do
    exec <>/dev/tty$tty
    respawn setsid $agetty 38400 tty$tty linux &
done
wait
