#!/bin/sh
name="hostname"

if [ "$1" != "start" ] ; then
    exit 0
fi

if [ -f /etc/hostname ] ; then
    cat /etc/hostname > /proc/sys/kernel/hostname
else
    echo "localhost.localdomain" > /proc/sys/kernel/hostname
fi